# Generated by Django 3.0.7 on 2020-08-28 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Nombre de la Categoria')),
                ('slug', models.SlugField(verbose_name='Slug de la Categoria')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_menu', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Producto')),
                ('slug', models.SlugField(verbose_name='Slug del Producto')),
                ('description', models.TextField(verbose_name='Descripción del Producto')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio del Producto')),
                ('photo', models.ImageField(upload_to='media/%Y/%m/%d', verbose_name='Imagen del Producto')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, verbose_name='Peso del Producto (en Kg)')),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Altura del Producto (en cm)')),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Anchura del Producto (en cm)')),
                ('available', models.BooleanField(default=True, verbose_name='¿Está disponible el Producto?')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Category', verbose_name='Categoria del Producto')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ('-created',),
            },
        ),
    ]
