# Generated by Django 3.0.7 on 2020-08-28 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='is_menu',
            field=models.BooleanField(default=False, verbose_name='¿Hace parte del menú de Navegacion?'),
        ),
    ]
